server:
  port: 9081
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:49161:XE
    username: GH_USER
    password: 123456
  jpa:
    database: oracle
    show-sql: true
  cloud:
    batch:
      initializer:
        enabled: false